version: '3'

services:
  api:
    build: ./api
    volumes:
      - "./api:/opt/api"
    ports:
      - "5000:5000"
    restart: always
  jupyter:
    build: ./api
    volumes:
      - "./jupyter:/opt/work"
    ports:
      - "8888:8888"
    restart: always
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser